name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: |
        export user_nuget=${{ secrets.nuget_user }}
        envsubst < './ClassLibrary1/nuget.config' | tee './ClassLibrary1/nuget.config'
        dotnet restore ./ClassLibrary1
    - name: Build
      run: dotnet build ./ClassLibrary1 --configuration Release --no-restore
    - name: Test
      run: dotnet test ./ClassLibrary1 --no-restore --verbosity normal
    - name: Nuget
      run: |
        export a='gkgk'+${{ secrets.nuget_user }}
        echo=a
        cd ./ClassLibrary1
        dotnet pack -c Release
        dotnet nuget push **/*.nupkg -s "github" -k ${{ secrets.nuget_user }}
