name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      working-directory: ./ClassLibrary1
      run: |
        export user_nuget=${{ secrets.nuget_user }}
        envsubst < 'nuget.config' | tee 'nuget.config'
        dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Nuget pack
      run: |
        envsubst < 'nuget.config' | tee 'nuget.config'
        dotnet pack -c Release
    - name: Nuget push
      run: dotnet nuget push **/*.nupkg -s "github" -k ${{ secrets.nuget_user }}
