name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/oleg-peresada/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.nuget_user }}
    - name: Install dependencies
      run: dotnet restore ./ClassLibrary1
    - name: Build
      run: dotnet build ./ClassLibrary1 --configuration Release --no-restore
    - name: Test
      run: dotnet test ./ClassLibrary1 --no-restore --verbosity normal
    - name: Nuget pack
      run: |
        cd ./ClassLibrary1
        envsubst < 'nuget.config' | tee 'nuget.config'
        dotnet pack -c Release
        dotnet nuget push **/*.nupkg -s "github" -k ${{ secrets.nuget_user }}
